version : '3'
#services: This is a keyword that indicates the beginning of the section where you define the different services (containers) you want to run.
services:
#database container
  db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - smarstore-data:/var/lib/postgresql/data
      # - mymongo-data-two:/data/db       #/data/db is thedefault path for mongodb, for postgres it will be differennt, for mysql also it will be different
  web-ecommerce-app:
    image: ajujacob/smarstore-ecommerce-api:0.0.1.RELEASE
    restart : always            #mongo express is relied on mongodb, so restart this until it establish a connection
    ports:
      - "3000:3000"
    #env_file: - .env: This line specifies that the service should read environment variables from a file named .env located in the same directory as the Docker Compose file. Environment variables are essential for configuring your application.
    env_file:
      - .env
    depends_on:
      - db
volumes:
  smarstore-data:
  #  driver: local
  # smartstore-data-two:
  #   driver: local