definitions:
  domain.Users:
    type: object
  model.AdminLoginInfo:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  model.NewAdminInfo:
    properties:
      email:
        description: Email    string `json:"email" validate:"required,email"`
        type: string
      password:
        type: string
      phone:
        maxLength: 10
        minLength: 10
        type: string
      user_name:
        type: string
    required:
    - email
    - password
    - phone
    - user_name
    type: object
  res.Response:
    properties:
      data: {}
      errors: {}
      message:
        type: string
      status_code:
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: Ecommerce REST API built using Go, PSQL, REST API following Clean Architecture.
  title: Ecommerce REST API
  version: "1.0"
paths:
  /admin/admins:
    post:
      consumes:
      - application/json
      description: Super admin can create a new admin from admin panel
      operationId: create-admin
      parameters:
      - description: New Admin Details
        in: body
        name: admin_details
        required: true
        schema:
          $ref: '#/definitions/model.NewAdminInfo'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Create a new admin from admin panel
      tags:
      - Admin
  /admin/login:
    post:
      consumes:
      - application/json
      description: Admin Login
      operationId: admin-login
      parameters:
      - description: Admin Login Credentials
        in: body
        name: admin_credentials
        required: true
        schema:
          $ref: '#/definitions/model.AdminLoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/res.Response'
      summary: Admin Login
      tags:
      - Admin
  /admin/logout:
    get:
      consumes:
      - application/json
      description: logout an logged-in admin from the site
      operationId: admin-logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/res.Response'
      summary: Admin_Logout
      tags:
      - Admin
  /user/signup:
    post:
      consumes:
      - application/json
      description: Create a new user with the specified details.
      operationId: Signup-user
      parameters:
      - description: User details
        in: body
        name: user_details
        required: true
        schema:
          $ref: '#/definitions/domain.Users'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/res.Response'
        "422":
          description: invalid input
      summary: api for Signup a new user
      tags:
      - Users Signup
swagger: "2.0"
