// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ajujacob88/go-ecommerce-gin-clean-arch/pkg/api"
	"github.com/ajujacob88/go-ecommerce-gin-clean-arch/pkg/api/handler"
	"github.com/ajujacob88/go-ecommerce-gin-clean-arch/pkg/config"
	"github.com/ajujacob88/go-ecommerce-gin-clean-arch/pkg/db"
	"github.com/ajujacob88/go-ecommerce-gin-clean-arch/pkg/repository"
	"github.com/ajujacob88/go-ecommerce-gin-clean-arch/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	otpRepository := repository.NewOTPRepository(gormDB)
	otpUseCase := usecase.NewOTPUseCase(otpRepository)
	userHandler := handler.NewUserHandler(userUseCase, otpUseCase)
	adminRepository := repository.NewAdminRepository(gormDB)
	adminUseCase := usecase.NewAdminUseCase(adminRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	productRepository := repository.NewProductRepository(gormDB)
	productUseCase := usecase.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productUseCase)
	cartRepository := repository.NewCartRepository(gormDB)
	cartUseCase := usecase.NewCartUseCase(cartRepository)
	cartHandler := handler.NewCartHandler(cartUseCase)
	orderRepository := repository.NewOrderRepository(gormDB, cartRepository)
	paymentRepository := repository.NewPaymentRepository(gormDB)
	paymentUseCase := usecase.NewPaymentUseCase(paymentRepository, orderRepository)
	couponRepository := repository.NewCouponRepository(gormDB)
	orderUseCase := usecase.NewOrderUseCase(orderRepository, paymentUseCase, userRepository, cartRepository, couponRepository)
	paymentHandler := handler.NewPaymentHandler(paymentUseCase, orderUseCase, cartUseCase)
	orderHandler := handler.NewOrderHandler(orderUseCase, paymentUseCase, cartUseCase, paymentHandler)
	couponUseCase := usecase.NewCouponUseCase(couponRepository, cartRepository)
	couponHandler := handler.NewCouponHandler(couponUseCase)
	serverHTTP := http.NewServerHTTP(userHandler, adminHandler, productHandler, cartHandler, orderHandler, paymentHandler, couponHandler)
	return serverHTTP, nil
}
