apiVersion: v1
kind: Service
metadata:
  name: smartstore-webapp-service
spec:
  type: NodePort
  selector:
    app: smartstore-webapp    
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
